### ISSUE TITLE
Mounted Weapons is broken with this mod installed

### ISSUE THREAD

**Issue by dounai2333** [TheBoogle/OldTarkovMovement#2]
Hi, I have noticed the mounted weapons (mounted grenade launcher and mounted heavy machine gun) have angle issue and cannot aim properly.
After the first time interact with the mounted heavy machine gun, you can no longer use it.
I'm using the "Modern Animation" mode.

The screenshot of bugged heavy machine gun (after the first time interact), you can interact with it but the game won't let you use it:
![2](https://github.com/user-attachments/assets/f68e8ce6-5c2b-4c9a-bb84-25d46ef0fcae)
![3](https://github.com/user-attachments/assets/fbf7ff1a-a088-47ca-9593-edeb713e1344)

**Comment by TheBoogle** [comment]
Fixed in 1.0.5
